# Generated by Django 2.1.1 on 2018-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopsQueryCopy',
            fields=[
                ('created', models.DateTimeField(blank=True, null=True)),
                ('nick', models.CharField(blank=True, max_length=20, null=True)),
                ('session_expired', models.DateTimeField(blank=True, null=True)),
                ('shop_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_site', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_url', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('sn', models.CharField(blank=True, db_column='SN', max_length=2, null=True, unique=True)),
            ],
            options={
                'db_table': 'shops.query_copy',
                'managed': False,
            },
        ),
    ]
