# Generated by Django 2.1.1 on 2018-09-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datess', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('account_name', models.CharField(max_length=32, verbose_name='账户名')),
                ('start_money', models.IntegerField(verbose_name='初始资金')),
                ('end_money', models.IntegerField(verbose_name='结余资金')),
                ('operator', models.CharField(max_length=16, verbose_name='操作员')),
                ('makes', models.CharField(max_length=5, verbose_name='运营确认')),
                ('start_money_img', models.ImageField(upload_to='img')),
                ('end_money_img', models.ImageField(upload_to='img')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=32, verbose_name='账户名')),
                ('brank_name', models.CharField(max_length=64, verbose_name='银行名')),
                ('brank_number', models.CharField(max_length=16, verbose_name='开户行号')),
                ('brank_card_number', models.CharField(max_length=22, verbose_name='银行卡号')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brush_single_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=32, verbose_name='店铺名')),
                ('wang_wang_number', models.CharField(max_length=32, verbose_name='旺旺号')),
                ('online_order_number', models.CharField(max_length=26, verbose_name='线上订单号')),
                ('transaction_data', models.CharField(max_length=16, verbose_name='成交日期')),
                ('payment_type', models.CharField(max_length=16, verbose_name='付款类型')),
                ('payment_amount', models.CharField(max_length=10, verbose_name='付款金额')),
                ('payment_account', models.CharField(max_length=32, verbose_name='付款账户')),
                ('operator', models.CharField(max_length=16, verbose_name='操作员')),
                ('remarks', models.CharField(max_length=64, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='操作日期')),
                ('operator', models.CharField(max_length=16, verbose_name='操作员')),
                ('operation_type', models.CharField(max_length=32, verbose_name='操作类型')),
                ('before_operation', models.CharField(max_length=200, verbose_name='操作前')),
                ('after_operation', models.CharField(max_length=200, verbose_name='操作后')),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=64, verbose_name='店铺名')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User_Brank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brank_operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Brank_account')),
            ],
        ),
        migrations.CreateModel(
            name='User_Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Shops')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=16, verbose_name='密码')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('rouse', models.CharField(max_length=8, verbose_name='角色')),
                ('description', models.CharField(max_length=32, verbose_name='职位描述')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='user_shops',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Userinfo'),
        ),
        migrations.AddField(
            model_name='user_brank',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Userinfo'),
        ),
    ]
