# Generated by Django 2.1.1 on 2018-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
