# Generated by Django 2.1.1 on 2018-10-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0002_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplemental_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(max_length=16, verbose_name='开启时间')),
                ('end_time', models.DateTimeField(max_length=16, verbose_name='关闭时间')),
                ('total_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Total_brank_account')),
            ],
        ),
        migrations.DeleteModel(
            name='Company_weixin',
        ),
    ]
