# Generated by Django 2.1.1 on 2018-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0002_auto_20180919_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_record',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='account_record',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='brank_account',
            name='brank_operator',
        ),
        migrations.RemoveField(
            model_name='brank_account',
            name='total_account_name',
        ),
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='own_total_brank',
        ),
        migrations.RemoveField(
            model_name='total_account_record',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='total_account_record',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='total_brank_account',
        ),
        migrations.DeleteModel(
            name='Account_record',
        ),
        migrations.DeleteModel(
            name='Brank_account',
        ),
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
        migrations.DeleteModel(
            name='Total_account_record',
        ),
        migrations.DeleteModel(
            name='Total_brank_account',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
