# Generated by Django 2.1.1 on 2018-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0002_auto_20180907_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=16, verbose_name='密码')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('rouse', models.CharField(max_length=8, verbose_name='角色')),
                ('description', models.CharField(max_length=32, verbose_name='职位描述')),
                ('deletes', models.CharField(max_length=5)),
                ('shop', models.ManyToManyField(to='brush.Shops')),
            ],
        ),
    ]
