# Generated by Django 2.1.1 on 2018-09-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brank_account',
        ),
    ]
