# Generated by Django 2.1.1 on 2018-09-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brush', '0003_auto_20180919_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datess', models.DateTimeField(verbose_name='创建日期')),
                ('start_money', models.IntegerField(verbose_name='初始资金')),
                ('end_money', models.IntegerField(verbose_name='结余资金')),
                ('weixin_withdraw_money', models.IntegerField(verbose_name='微信提现手续费')),
                ('makes', models.CharField(max_length=5, verbose_name='运营确认')),
                ('start_money_img', models.ImageField(upload_to='start_img')),
                ('end_money_img', models.ImageField(upload_to='end_img')),
                ('weixin_img', models.ImageField(upload_to='weixin_img')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=64, verbose_name='账户名')),
                ('brank_name', models.CharField(max_length=64, verbose_name='银行名')),
                ('brank_number', models.CharField(max_length=32, verbose_name='开户行号')),
                ('brank_card_number', models.CharField(max_length=32, verbose_name='银行卡号')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brush_single_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=32, verbose_name='店铺名')),
                ('qq_or_weixin', models.CharField(max_length=32, verbose_name='QQ或微信')),
                ('wang_wang_number', models.CharField(max_length=32, verbose_name='旺旺号')),
                ('online_order_number', models.CharField(max_length=26, verbose_name='线上订单号')),
                ('transaction_data', models.CharField(max_length=16, verbose_name='成交日期')),
                ('payment_type', models.CharField(max_length=16, verbose_name='付款类型')),
                ('payment_amount', models.CharField(max_length=10, verbose_name='付款金额')),
                ('remarks', models.CharField(max_length=64, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='操作日期')),
                ('operation_type', models.CharField(max_length=32, verbose_name='操作类型')),
                ('before_operation', models.CharField(max_length=500, verbose_name='操作前')),
                ('after_operation', models.CharField(max_length=500, verbose_name='操作后')),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=64, verbose_name='店铺名')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Total_account_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datess', models.DateTimeField(verbose_name='创建日期')),
                ('start_money', models.IntegerField(verbose_name='初始资金')),
                ('end_money', models.IntegerField(verbose_name='结余资金')),
                ('makes', models.CharField(max_length=5, verbose_name='运营确认')),
                ('start_money_img', models.ImageField(upload_to='start_img')),
                ('end_money_img', models.ImageField(upload_to='end_img')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Total_brank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datess', models.DateTimeField(verbose_name='创建日期')),
                ('total_account_name', models.CharField(max_length=64, verbose_name='总账户名')),
                ('total_brank_name', models.CharField(max_length=64, verbose_name='银行名')),
                ('total_brank_number', models.CharField(max_length=32, verbose_name='开户行号')),
                ('total_brank_card_number', models.CharField(max_length=32, verbose_name='银行卡号')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=16, verbose_name='密码')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('rouse', models.CharField(max_length=8, verbose_name='角色')),
                ('description', models.CharField(max_length=64, verbose_name='职位描述')),
                ('deletes', models.CharField(max_length=5)),
                ('shop', models.ManyToManyField(to='brush.Shops')),
                ('total_brank_account', models.ManyToManyField(to='brush.Total_brank_account')),
            ],
        ),
        migrations.AddField(
            model_name='total_account_record',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Total_brank_account'),
        ),
        migrations.AddField(
            model_name='total_account_record',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Userinfo'),
        ),
        migrations.AddField(
            model_name='shops',
            name='own_total_brank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Total_brank_account'),
        ),
        migrations.AddField(
            model_name='log',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Userinfo'),
        ),
        migrations.AddField(
            model_name='brush_single_entry',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Userinfo'),
        ),
        migrations.AddField(
            model_name='brush_single_entry',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Brank_account'),
        ),
        migrations.AddField(
            model_name='brank_account',
            name='brank_operator',
            field=models.ManyToManyField(to='brush.Userinfo'),
        ),
        migrations.AddField(
            model_name='brank_account',
            name='total_account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Total_brank_account'),
        ),
        migrations.AddField(
            model_name='account_record',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Brank_account'),
        ),
        migrations.AddField(
            model_name='account_record',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush.Userinfo'),
        ),
    ]
