# Generated by Django 2.1.1 on 2018-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0004_delete_brank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=32, verbose_name='账户名')),
                ('brank_name', models.CharField(max_length=64, verbose_name='银行名')),
                ('brank_number', models.CharField(max_length=16, verbose_name='开户行号')),
                ('brank_card_number', models.CharField(max_length=22, verbose_name='银行卡号')),
                ('deletes', models.CharField(max_length=5)),
                ('brank_operator', models.ManyToManyField(to='brush.Userinfo')),
            ],
        ),
    ]
