# Generated by Django 2.1.1 on 2018-09-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0005_brank_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
    ]
