# Generated by Django 2.1.1 on 2018-09-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0007_brush_single_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
    ]
