# Generated by Django 2.1.1 on 2018-09-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0009_brush_single_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_record',
        ),
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
