# Generated by Django 2.1.1 on 2018-09-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0011_account_record_brush_single_entry_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
    ]
