# Generated by Django 2.1.1 on 2018-09-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0012_auto_20180914_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brush_single_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=32, verbose_name='店铺名')),
                ('qq_or_weixin', models.CharField(max_length=32, verbose_name='QQ或微信')),
                ('wang_wang_number', models.CharField(max_length=32, verbose_name='旺旺号')),
                ('online_order_number', models.CharField(max_length=26, verbose_name='线上订单号')),
                ('transaction_data', models.CharField(max_length=16, verbose_name='成交日期')),
                ('payment_type', models.CharField(max_length=16, verbose_name='付款类型')),
                ('payment_amount', models.CharField(max_length=10, verbose_name='付款金额')),
                ('remarks', models.CharField(max_length=64, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('deletes', models.CharField(max_length=5)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Userinfo')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Brank_account')),
            ],
        ),
    ]
