# Generated by Django 2.1.1 on 2018-09-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0013_brush_single_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_record',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='account_record',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='log',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Account_record',
        ),
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
