# Generated by Django 2.1.1 on 2018-09-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0015_account_record_brush_single_entry_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_record',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='account_record',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Account_record',
        ),
    ]
