# Generated by Django 2.1.1 on 2018-09-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0016_auto_20180914_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datess', models.DateTimeField(verbose_name='创建日期')),
                ('start_money', models.IntegerField(verbose_name='初始资金')),
                ('end_money', models.IntegerField(verbose_name='结余资金')),
                ('makes', models.CharField(max_length=5, verbose_name='运营确认')),
                ('start_money_img', models.ImageField(upload_to='img')),
                ('end_money_img', models.ImageField(upload_to='img')),
                ('deletes', models.CharField(max_length=5)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Brank_account')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Userinfo')),
            ],
        ),
    ]
