# Generated by Django 2.1.1 on 2018-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0017_account_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_record',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='account_record',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='brank_account',
            name='brank_operator',
        ),
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='brush_single_entry',
            name='payment_account',
        ),
        migrations.AlterField(
            model_name='log',
            name='after_operation',
            field=models.CharField(max_length=500, verbose_name='操作后'),
        ),
        migrations.AlterField(
            model_name='log',
            name='before_operation',
            field=models.CharField(max_length=500, verbose_name='操作前'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='description',
            field=models.CharField(max_length=64, verbose_name='职位描述'),
        ),
        migrations.DeleteModel(
            name='Account_record',
        ),
        migrations.DeleteModel(
            name='Brank_account',
        ),
        migrations.DeleteModel(
            name='Brush_single_entry',
        ),
    ]
