# Generated by Django 2.1.1 on 2018-09-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush', '0018_auto_20180919_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datess', models.DateTimeField(verbose_name='创建日期')),
                ('start_money', models.IntegerField(verbose_name='初始资金')),
                ('end_money', models.IntegerField(verbose_name='结余资金')),
                ('weixin_withdraw_money', models.IntegerField(verbose_name='微信提现手续费')),
                ('makes', models.CharField(max_length=5, verbose_name='运营确认')),
                ('start_money_img', models.ImageField(upload_to='start_img')),
                ('end_money_img', models.ImageField(upload_to='end_img')),
                ('weixin_img', models.ImageField(upload_to='weixin_img')),
                ('deletes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=64, verbose_name='账户名')),
                ('brank_name', models.CharField(max_length=64, verbose_name='银行名')),
                ('brank_number', models.CharField(max_length=32, verbose_name='开户行号')),
                ('brank_card_number', models.CharField(max_length=32, verbose_name='银行卡号')),
                ('deletes', models.CharField(max_length=5)),
                ('brank_operator', models.ManyToManyField(to='brush.Userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Brush_single_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=32, verbose_name='店铺名')),
                ('qq_or_weixin', models.CharField(max_length=32, verbose_name='QQ或微信')),
                ('wang_wang_number', models.CharField(max_length=32, verbose_name='旺旺号')),
                ('online_order_number', models.CharField(max_length=26, verbose_name='线上订单号')),
                ('transaction_data', models.CharField(max_length=16, verbose_name='成交日期')),
                ('payment_type', models.CharField(max_length=16, verbose_name='付款类型')),
                ('payment_amount', models.CharField(max_length=10, verbose_name='付款金额')),
                ('remarks', models.CharField(max_length=64, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('deletes', models.CharField(max_length=5)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Userinfo')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Brank_account')),
            ],
        ),
        migrations.CreateModel(
            name='Total_brank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_account_name', models.CharField(max_length=64, verbose_name='总账户名')),
                ('own_shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Shops')),
            ],
        ),
        migrations.AddField(
            model_name='brank_account',
            name='total_account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Total_brank_account'),
        ),
        migrations.AddField(
            model_name='account_record',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Brank_account'),
        ),
        migrations.AddField(
            model_name='account_record',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brush.Userinfo'),
        ),
    ]
